### ISSUE TITLE
Animated gifs

### ISSUE THREAD

**Issue by afharvey** [ushis/resize-demo#1]
I've not yet found a nice way to resize animated gifs. nfnt/resize only affects the first frame. Some people loop through them and resize each one.. which is a bit slow. Some projects have wrapped Imagick and gifiy.

**Comment by ushis** [comment]
i think you should post that issue here: https://github.com/nfnt/resize :)

**Comment by ushis** [comment]
i am going to close that issue for now, because i am not going to fix that, because its just a demo of nfnt/resize... reopen if you wish further discussion...
